version: "2"
services:
  sails.mongo:
    image: tutum/mongodb:3.0
    ports:
    - "27017:27017"
    - "28017:28017"
    restart: always
    volumes:
      - sails_db:/data/db
    env_file:
      - ./variables.env
volumes:
  sails_db:
